imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    translator:      ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        default_field:  "melanoma"
        default_entityType: "keywords"
        default_keywordSearch:  "metastasis"
        default_geneSearch: "BRAF"
        default_mutationSearch: "V599E"
        default_wildTypeMutationInput: "A"
        default_positionMutationInput: 158
        default_mutantMutationInput: "Whatever"
        default_chemicalSearch: "vemurafenib"
        default_diseaseSearch: "Parkinson"
        default_mutatedProteinSearch: "BRAF"
        default_otherCancerSearch: "metastasis"
        default_mutatedProteinMeshIdSearch: "{default_mutatedProtein_MeshId_search_value}"
        default_whatToSearch_keyword:  "any"
        default_source:   "all"
        mouseover_source: "Document source used (PubMed abstracts/sentences, full text articles, NDAs or EPARs)"
        mouseover_svm: "Sort by SVM score. Binary linear kernel SVM classifier score result (SVMLight).Features: word unigram, stop word filter, balanced training set. The higher the more related to the topic. If the output of the scoring function is positive then the text was classified as relevant for adverse hepatobiliary events, while if it has a negative score it was classified as non-relevant. See: http://svmlight.joachims.org"
        mouseover_conf: "Sort by SVM confidence score. Binary linear kernel SVM classifier confidence scores (scikit-learn).Features: word 1-4grams, stop word filter, tf-idf weights, balanced training set. The higher the more related to the topic. If the output of the scoring function is positive then the text was classified as relevant for adverse hepatobiliary events, while if it has a negative score it was classified as non-relevant. (See: http://scikit-learn.org and decision_function)"
        mouseover_pattern: "Sort by pattern score. Number of adverse hepatobiliary event text patterns detected."
        mouseover_term: "Sort by term score. Number of adverse hepatobiliary event terms/phrases detected."
        mouseover_rule: "Sort by rule score.  Scores of 0.01 correspond to sentences that only mention a term or phrase related to the hepatobiliary system. Scores > 0.01 correspond to sentences that also contain adverse, toxic or disease events. The rule score is a heuristic score that takes into account: (1) the number of co-occurrences between hepatobiliary terms and adverse effect terms in a sentences, (2) their respective relative order within the sentence and (3) their relative distance measured by the number of word tokens between them."
        mouseover_nephro: "Sort by nephrotoxicity score. Binary linear kernel SVM classifier score result (SVMLight).Features: word unigram, stop word filter, balanced training set. The higher the more related to the topic. If the output of the scoring function is positive then the text was classified as relevant for adverse nephrologic events, while if it has a negative score it was classified as non-relevant. See: http://svmlight.joachims.org"
        mouseover_cardio: "Sort by cardiotoxicity score. Binary linear kernel SVM classifier score result (SVMLight).Features: word unigram, stop word filter, balanced training set. The higher the more related to the topic. If the output of the scoring function is positive then the text was classified as relevant for adverse cardio events, while if it has a negative score it was classified as non-relevant. See: http://svmlight.joachims.org"
        mouseover_thyro: "Sort by thyrotoxicity score. Binary linear kernel SVM classifier score result (SVMLight).Features: word unigram, stop word filter, balanced training set. The higher the more related to the topic. If the output of the scoring function is positive then the text was classified as relevant for adverse thyroid events, while if it has a negative score it was classified as non-relevant. See: http://svmlight.joachims.org"
        mouseover_phospho: "Sort by phospholipidosis score. Binary linear kernel SVM classifier score result (SVMLight).Features: word unigram, stop word filter, balanced training set. The higher the more related to the topic. If the output of the scoring function is positive then the text was classified as relevant for adverse phospholipidic events, while if it has a negative score it was classified as non-relevant. See: http://svmlight.joachims.org"
        mouseover_curation: "Manually validated item."
        mouseover_compound_relation_compound: "Chemical compound or drug"
        mouseover_compound_relation_relation: "Association between chemical compounds/drugs and adverse hepatobiliary events."
        mouseover_compound_relation_term: "Adverse hepatobiliary term or phrase. These correspond to terms extracted from controlled vocabularies (COSTART, HumanPhenotype, MeDRA, eTOX-IMIM, etc.) as well as derived directly from the literature using noun-phrase extraction and a rule based system for term prioritization."
        mouseover_compound_relation_score:  "chemical compound-adverse hepatobiliary term association score. In case the relation was detected by a pattern based method (high precision) a score of 1 is provided, otherwise the SVM confidence score is provided, corresponding to the scikit-learn.org decision_function result of a binary linear kernel SVM trained using as positive training data sentences detected by the pattern based method."
        mouseover_compound_relation_qualifier: "The relation qualifier refers to affirmed or negated relationships between the entities. AA: (chemical affirmed, term affirmed); AN:  (chemical affirmed, term negated); NA: (chemical negated, term affirmed); NN:  (chemical negated, term negated)"
        mouseover_cytochrome_relation_compound: "Chemical compound or drug"
        mouseover_cytochrome_relation_relation: "Association between chemical compounds/drugs and Cytochromes P450 (CYPs)."
        mouseover_cytochrome_relation_cytochrome: "Cytochromes P450 (CYPs) (e.g. CYP3A4, CYP2C8, CYP2B6). It covers CYPs from humans and the 37 main mammalian animal models used in toxicology studies."
        mouseover_cytochrome_relation_induction: "Sort by induction/activation/enhancement relationship score. 3: relationship detected by both a pattern based approach and a SVM sentences classifier; 2: relationship detected only by the pattern based approach; 1: relationship detected only by the SVM sentence classifier approach; 0: not detected by neither of both."
        mouseover_cytochrome_relation_inhibition: "Sort by inhibition/repression/inactivation relationship score. 3: relationship detected by both a pattern based approach and a SVM sentences classifier; 2: relationship detected only by the pattern based approach; 1: relationship detected only by the SVM sentence classifier approach; 0: not detected by neither of both."
        mouseover_cytochrome_relation_metabolism: "Sort by metabolism/substrate/product relationship score. 3: relationship detected by both a pattern based approach and a SVM sentences classifier; 2: relationship detected only by the pattern based approach; 1: relationship detected only by the SVM sentence classifier approach; 0: not detected by neither of both."
        mouseover_cytochrome_relation_qualifier: "The relation qualifier refers to affirmed or negated relationships.AA: (chemical affirmed, CYPs affirmed); AN:  (chemical affirmed, CYPs negated); NA: (chemical negated, CYPs affirmed); NN:  (chemical negated, CYPs negated)"
        mouseover_marker_relation_compound: "Chemical compound or drug"
        mouseover_marker_relation_relation: "Association between chemical compounds/drugs and liver biochemical markers (e.g. ALT, AST, SDH, GGT)"
        mouseover_marker_relation_marker: "Correspond to one of 17 enzymes and chemical compounds assayed as biochemical markers of adverse liver reactions (e.g. ALT, AST, SDH, GGT). Also a unspecific term was included (liver tests)."
        mouseover_marker_relation_score: "Chemical-marker relation score. If the relation was detected by a pattern based approach the score is 1, otherwise a SVM relationship sentence classifier score is provided."
        mouseover_marker_relation_qualifier: "The relation qualifier refers to affirmed or negated relationships. AA: (chemical affirmed, marker affirmed); AN:  (chemical affirmed, marker negated); NA: (chemical negated, marker affirmed); NN:  (chemical negated, marker negated)"
        mouseover_relation_curation: "Manually validated item."


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    #host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#Elasticsearch configuration
fos_elastica:
    clients:
        default: { host: limtox.cnio.es, port: 9205 }
    indexes:
        melanomamine:
            client: default
            finder: ~
            types:
                abstracts:
                    mappings:
                        pmid:
                            type: string
                        title:
                            boost: 3
                            type: string
                        text:
                            boost: 5
                            type: string
                        melanoma_score_2:
                            boost: 2
                            type: float
                        genes3:
                            type: nested
                            include_in_parent: true
                            properties:
                                startMention:
                                    type: integer
                                endMention:
                                    type: integer
                                mention:
                                    type: string
                                typeOf:
                                    type: string
                                geneId:
                                    type: string
                                taxonId:
                                    type: string
                                existEvidence:
                                    type: integer
                    persistence:
                        driver: orm
                        model: Melanomamine\DocumentBundle\Entity\Abstracts
                        provider: ~
                        finder: ~
                        listener:
                            insert: true
                            update: true
                            delete: true
                genesDictionary:
                    mappings:
                        ncbiGeneId:
                            type: long
                        geneProteinName:
                            type: string
                        ncbiTaxId:
                            type: integer
                chemicalsDictionary:
                    mappings:
                        chemicalName:
                            type: string
                        casrn:
                            type: string
                        chebi:
                            type: string
                        chemIdPlus:
                            type: string
                        chemicalClass:
                            type: string
                        chemicalName:
                            type: string
                        drugbank:
                            type: string
                        hmdb:
                            type: string
                        inchi:
                            type: string
                        keggCompound:
                            type: string
                        keggDrug:
                            type: string
                        mesh:
                            type: string
                        pubChemSid:
                            type: string
            settings:
                index:
                  analysis:
                        analyzer:
                            my_analyzer:
                                type: snowball
                                language: English

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Melanomamine\UserBundle\Entity\User
    registration:
        confirmation:
            enabled:    true
            from_email:
                address:    acanada@cnio.es
                sender_name:    Limtox Registration
    resetting:
        email:
            from_email:
                address:    acanada@cnio.es
                sender_name:    Limtox Resetting
    from_email:
        address:    noreply@limtox.com
        sender_name:    Limtox


# Dependency container global parameters
parameters:
    melanomamine.total_documents_elasticsearch_retrieval: 1000
    melanomamine.evidences_per_page: 10
    melanomamine.summaries_per_page: 50
    melanomamine.number_of_pages: 15
