
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

homepage:
    pattern: /
    defaults: { _controller: MelanomamineFrontendBundle:Default:home}

search:
    pattern: /search/
    defaults: { _controller: MelanomamineFrontendBundle:Search:search}

search_keywords:
    pattern: /search/keywords/{whatToSearch}/{entityName}/
    defaults: { _controller: MelanomamineFrontendBundle:Search:searchKeywords}

search_genes:
    pattern: /search/genes/{whatToSearch}/{entityName}/{specie}/
    defaults: { _controller: MelanomamineFrontendBundle:Search:searchGenes, specie: "human"}

search_genes_expanded:
    pattern: /search/genes_expanded/{whatToSearch}/{entityName}/{specie}/{searchTerm}/
    defaults: { _controller: MelanomamineFrontendBundle:Search:searchGenesExpanded}

search_mutations:
    pattern: /search/mutations/{whatToSearch}/{entityName}/{dna}/{protein}/
    defaults: { _controller: MelanomamineFrontendBundle:Search:searchMutations, dna: "false", protein: "false"}


search_chemicals:
    pattern: /search/chemicals/{whatToSearch}/{entityName}/{queryExpansion}/
    defaults: { _controller: MelanomamineFrontendBundle:Search:searchChemicals, queryExpansion: "false"}

search_diseases:
    pattern: /search/diseases/{whatToSearch}/{entityName}/
    defaults: { _controller: MelanomamineFrontendBundle:Search:searchDiseases}

search_mutatedProteins:
    pattern: /search/mutatedProteins/{whatToSearch}/{entityName}/{specie}/
    defaults: { _controller: MelanomamineFrontendBundle:Search:searchMutatedProteins}





#elasticSearch_search_entityType:
#    pattern: /search/{entityType}/{entityName}/
#    defaults: { _controller: MelanomamineFrontendBundle:Search:searchEntityType}