parameters:
    melanomamine.chemspider.class: Melanomamine\FrontendBundle\Controller\ChemspiderController
services:
    melanomamine.searchChemSpider:
        class: "%melanomamine.chemspider.class%"
        arguments: ["@service_container"]