<?php

namespace Melanomamine\DocumentBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AbstractsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AbstractsRepository extends EntityRepository
{
}
